#Include 'Protheus.ch'
//---------------------------------------------------------------------------------------------------------------------------
/*/{Protheus.doc} MA020ALT
(long_description)
@type function
@author Cris
@since 03/08/2017
@version 1.0
@return ${return}, ${return_description}
@example
(examples)
@see http://tdn.totvs.com.br/pages/releaseview.action?pageId=6087594
/*///---------------------------------------------------------------------------------------------------------------------------
User Function MA020ALT()

	Local lVld	:= .T.
	
		lVld	:= U_SA2VLD01()

Return lVld